---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: custom-fedora-atomic
# description will be included in the image's metadata
description: This image is based on Bazzite which opinaites and removes the packages that I deem are not useful in the default system installation.
base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - kde-partitionmanager
        - podman-compose
        - libreoffice-TexMaths
        - libreoffice-base
        - libreoffice-calc
        - libreoffice-core
        - libreoffice-draw
        - libreoffice-data
        - libreoffice-emailmerge
        - libreoffice-graphicfilter
    remove:
      packages:
        - steam
        - lutris
        - bazaar
        - webapp-manager
        - Scopebuddy
        - mangohud.x86_64
        - mangohud.i686
        - terra-gamescope.x86_64
        - terra-gamescope.i686
        - openxr
        - krunner-bazaar
        - gnome-disk-utility
        - fcitx5-chewing
        - fcitx5-mozc
        - fcitx5-chinese-addons
        - fcitx5-m17n
        - fcitx5-hangul
        - kcm-fcitx5
        - iwd


  - type: default-flatpaks
    configurations:
      - notify: true 
        scope: system
        install:
          - app.zen_browser.zen
          - com.vscodium.codium-insiders
          - io.github.kolunmi.Bazaar
          - org.fkoehler.KTailctl
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal
      - scope: user 
        install:
          - com.valvesoftware.Steam
          - net.davidotek.pupgui2
          - com.valvesoftware.Steam.Utility.InhibitScreensaver
          - com.valvesoftware.Steam.Utility.steamtinkerlaunch
          - com.heroicgameslauncher.hgl

  - type: script
    scripts:
      - disable-flatpak-installer.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
